# Import the load_dotenv() function from the python-dotenv library.
# This function reads all the variables stored inside a .env file
# and loads them into the program as environment variables.
# It is commonly used to keep sensitive information like API keys
# outside of the source code for better security.
from dotenv import load_dotenv

# Import Python's built-in os module.
# The os module provides many operating system-related utilities.
# In this program, we use it to read environment variables,
# specifically our API key stored inside the .env file.
import os

# Import the Groq client class.
# This class allows our Python program to establish a connection
# with Groq's servers so we can send prompts to an AI model
# and receive AI-generated responses.
from groq import Groq


# Load all environment variables from the .env file.
# After this line executes, every variable defined inside
# the .env file becomes accessible through os.getenv().
# Without calling load_dotenv(), Python would not know
# about the variables stored inside the .env file.
load_dotenv()


# Retrieve the value of the environment variable named "API".
# The value stored in the .env file is assigned to the variable
# named my_api. If the variable does not exist, os.getenv()
# returns None.
my_api = os.getenv("API")


# Check whether the API key was successfully loaded.
# Since the API key is required to communicate with Groq's API,
# the program should stop immediately if it cannot find one.
if not my_api:

    # Raise a ValueError exception with a meaningful error message.
    # This prevents the program from continuing without authentication,
    # which would eventually cause an API request to fail.
    raise ValueError("No API found")

else:

    # If the API key exists, print a confirmation message.
    # This is useful during development because it confirms
    # that the .env file has been loaded correctly.
    print("API Found!!!")


# Create an instance of the Groq client.
# The API key is passed during initialization so every future
# request sent through this client is authenticated automatically.
client = Groq(api_key=my_api)


# Store the name of the Large Language Model (LLM) that we want
# Groq to use for generating responses.
# Different models have different capabilities, speeds, and costs.
model_ = "llama-3.3-70b-versatile"


# Define the role of the message.
# Since this message is written by the user, the role is "user".
# Other possible roles include "assistant" and "system".
rolez = "user"


# Store the question or instruction that we want to send
# to the AI model. This is called the prompt.
prompt = "What is HEAP in DSA?"


# Create a list of messages.
# Groq's Chat Completion API expects the conversation history
# to be provided as a list, where each element is a dictionary
# representing one message in the conversation.
messages = [

    {
        # Specify who is sending this message.
        # Here, the sender is the user.
        "role": rolez,

        # Store the actual text that will be processed by the AI model.
        "content": prompt
    }

]


# Send the conversation to Groq's Chat Completion API.
# The model parameter tells Groq which AI model to use.
# The messages parameter contains the conversation history.
# Once the request is processed, the API returns a response object
# containing the generated answer and additional metadata.
response = client.chat.completions.create(

    model=model_,

    messages=messages

)


# Print only the text generated by the AI model.
# The response object contains many details, but the actual
# answer is stored inside response.choices[0].message.content.
# This is the part most applications display to the user.
print(response.choices[0].message.content)


# print(response) ---> If only using this, the LLM returns the entire response object,
# including the generated answer, token usage, model information, response ID,
# finish reason, and other metadata. To print only the AI's answer,
# use response.choices[0].message.content.


#__________________________________________________________________________________________#
# This is the fundamental building block of modern Generative AI development.
# By mastering this workflow, you can create scalable AI-powered applications such as
# conversational assistants, Retrieval-Augmented Generation (RAG) systems,
# AI agents, document intelligence platforms, customer support bots,
# code assistants, workflow automations, and enterprise AI solutions.
